import {state,$,$$,api,escape,card,poll,search,wireSearch,bind,pending,dialog,notice,copyDialog,stamp,humanBytes} from './ui.js';
let publicSession=null;const tickets=new Map();
export function clearCrusher(){publicSession=null;tickets.clear();}
export function hashFile(file,onProgress=()=>{},signal=state.viewController?.signal){return new Promise((resolve,reject)=>{if(signal?.aborted){reject(new DOMException('Cancelled','AbortError'));return;}const worker=new Worker('/assets/hash-worker.js',{type:'module'});function finish(error,digest){worker.terminate();signal?.removeEventListener('abort',abort);if(error)reject(error);else resolve(digest);}function abort(){finish(new DOMException('Cancelled','AbortError'));}signal?.addEventListener('abort',abort,{once:true});worker.onmessage=e=>{if(e.data.sha256)finish(null,e.data.sha256);else if(e.data.error)finish(Error(e.data.error));else onProgress(e.data.progress);};worker.onerror=()=>finish(Error('File hashing failed.'));worker.postMessage(file);});}

export async function resourcePicker(select){const modal=dialog('Select Saturn source',`<div class="toolbar"><button data-parent>Parent folder</button><span data-path class="collection-info">root</span></div><div class="list" data-files></div><button data-more hidden>Next page</button>`,{dirtyGuard:false});let current='root',cursor=null;
  async function load(path,next=null){const result=await api('/api/owner/resources?'+new URLSearchParams({path,limit:'100',...(next?{cursor:next}:{})}));if(!modal.element.isConnected)return;current=path;cursor=result.next_cursor;$('[data-path]',modal.element).textContent=path;$('[data-parent]',modal.element).disabled=path==='root';$('[data-more]',modal.element).hidden=!cursor;$('[data-files]',modal.element).innerHTML=result.entries.length?result.entries.map(item=>`<div class="list-row"><span>${escape(item.path.split('/').at(-1))}</span><small>${item.type==='folder'?'Folder':escape(humanBytes(item.size_bytes))}</small><button data-file="${escape(item.path)}" data-kind="${item.type}">${item.type==='folder'?'Open folder':'Select file'}</button></div>`).join(''):'<p class="empty">This folder is empty.</p>';}
  bind(modal.element,'click','[data-file]',async(e,b)=>{if(b.dataset.kind==='folder')await load(b.dataset.file);else{select(b.dataset.file);modal.close(true);}});bind(modal.element,'click','[data-parent]',()=>load(current.split('/').slice(0,-1).join('/')||'root'));bind(modal.element,'click','[data-more]',()=>load(current,cursor));try{await load('root');}catch(error){modal.error.textContent=error.message;}}

export async function crusher(root,{publicOnly=false}={}){
  const authHeaders=()=>publicOnly&&publicSession?{Authorization:'Bearer '+publicSession.token}:{};
  async function request(route,options={}){return api('/api/v1/crusher'+route,{...options,headers:{...authHeaders(),...options.headers},allow401:publicOnly});}
  if(publicOnly&&!publicSession){root.innerHTML=`<section class="card wide"><div class="card-body"><h2>Submit a source</h2><p>Use a one-time access code from the owner.</p><form class="group"><label>Crusher access code<input name="code" autocomplete="off" required></label><button type="submit">Activate code</button><p class="error-message" role="alert"></p></form></div></section>`;$('form',root).onsubmit=async e=>{e.preventDefault();await pending($('button',root),async()=>{try{publicSession=await request('/sessions',{method:'POST',body:{code:$('[name=code]',root).value}});document.dispatchEvent(new Event('crusher-activated'));}catch(error){$('.error-message',root).textContent=error.message;}});};return()=>{};}
  root.innerHTML=`<div class="grid">${card('source','Source',`<form class="crusher-input"><div class="row"><label class="grow">Source type<select name="type" aria-label="Source type"><option value="text">Text</option><option value="url">Web page</option><option value="upload">File</option><option value="youtube">YouTube</option><option value="git">Git repository</option>${publicOnly?'':'<option value="saturn">Saturn file</option>'}</select></label>${publicOnly?'':'<button type="button" data-access>Create access code</button>'}</div><label data-text>Source text<textarea name="text" spellcheck="false"></textarea></label><label data-url hidden>Source URL<input name="url" type="url" placeholder="https://…"></label><label data-upload hidden>Source file (up to 2 GiB)<input name="file" type="file"></label><div data-saturn hidden><button type="button" data-pick>Choose a Saturn file</button><p data-selected>No file selected.</p></div><button type="submit">Submit source</button><p data-submit-status role="status"></p><p class="error-message" role="alert"></p></form>`,{wide:true})}${card('submissions','Submissions',`<div class="toolbar">${search('Search submissions','Filter this page by source or stage')}<div class="collection-info" data-count></div><button data-previous disabled>Previous</button><button data-next>Next</button></div><div class="list" data-jobs></div>`,{wide:true})}</div>`;
  $$('.drag,.ordinal',root).forEach(node=>node.remove());const form=$('form',root);let chosen=null,records=[],query='',offset=0,acceptance=null;
  form.elements.type.onchange=()=>{const kind=form.elements.type.value;for(const name of ['text','url','upload','saturn'])$('[data-'+name+']',root).hidden=name==='url'?!['url','youtube','git'].includes(kind):name!==kind;};
  bind(root,'click','[data-access]',(e,b)=>pending(b,async()=>{const result=await request('/access',{method:'POST',body:{}});copyDialog('Crusher access code',result.code,'One use. Expires '+stamp(result.expires_at)+'. Open '+location.origin+'/crusher to submit sources.');}));
  bind(root,'click','[data-pick]',()=>resourcePicker(path=>{chosen=path;$('[data-selected]',root).textContent=path;}));
  function render(){const visible=records.filter(job=>(job.source_label+' '+job.state+' '+job.stage+' '+job.job_id).toLowerCase().includes(query.toLowerCase()));$('[data-count]',root).textContent=visible.length+' of '+records.length+' on page '+(offset/100+1);$('[data-jobs]',root).innerHTML=visible.length?visible.map(job=>`<section class="job"><div class="job-head"><strong>${escape(job.source_label)}</strong><span>${escape(job.state)} · ${job.progress_percent}%</span></div><p>${escape(job.stage.replaceAll('_',' '))}</p><div class="progress" role="progressbar" aria-label="Processing ${escape(job.source_label)}" aria-valuemin="0" aria-valuemax="100" aria-valuenow="${job.progress_percent}"><span style="width:${job.progress_percent}%"></span></div><small>Submitted ${escape(stamp(job.created_at))} · ${escape(job.job_id)}</small>${job.error?'<p class="danger">'+escape(job.error.message||job.error.code||'Processing failed')+'</p>':''}</section>`).join(''):'<p class="empty">No submissions on this page.</p>';$('[data-previous]',root).disabled=!offset;$('[data-next]',root).disabled=records.length<100;}
  async function refresh(){try{records=await request('/jobs?limit=100&offset='+offset);}catch(error){if(!publicOnly||error.status!==401)throw error;records=await Promise.all([...tickets].slice(-100).map(([id,ticket])=>request('/jobs/'+id,{headers:{'X-Crusher-Status-Ticket':ticket}})));$('[data-submit-status]',root).textContent='Submission session expired. Existing receipts remain available in this tab.';$('button[type=submit]',root).disabled=true;}if(root.isConnected)render();}
  wireSearch($('.search-box',root),value=>{query=value;render();});bind(root,'click','[data-previous]',async()=>{offset=Math.max(0,offset-100);await refresh();});bind(root,'click','[data-next]',async()=>{offset+=100;await refresh();});
  form.onsubmit=async e=>{e.preventDefault();await pending($('button[type=submit]',form),async()=>{const status=$('[data-submit-status]',root),error=$('.error-message',form);error.textContent='';const controls=[...form.elements].map(node=>[node,node.disabled]);for(const [node] of controls)node.disabled=true;try{const kind=form.elements.type.value,fileIdentity=form.elements.file.files[0];const signature=JSON.stringify([kind,form.elements.text.value,form.elements.url.value,chosen]);let source={type:kind};
      if(acceptance&&acceptance.signature===signature&&acceptance.file===fileIdentity)source=acceptance.source;
      else{
      if(kind==='text')source.text=form.elements.text.value;else if(['url','youtube','git'].includes(kind))source.url=form.elements.url.value;else if(kind==='saturn'){if(!chosen)throw Error('Select a Saturn file.');source.path=chosen;}else{const file=form.elements.file.files[0];if(!file)throw Error('Choose a source file.');if(file.size>2*1024**3)throw Error('The source file exceeds 2 GiB.');status.textContent='Checking file integrity…';const sha=await hashFile(file,p=>status.textContent='Checking file integrity · '+Math.round(p*100)+'%');const upload=await request('/uploads',{method:'POST',body:{name:file.name,size:file.size}});status.textContent='Uploading source…';const response=await fetch('/api/v1/crusher/uploads/'+upload.upload_id+'/content',{method:'PUT',body:file,signal:state.viewController?.signal,credentials:'same-origin',headers:{...authHeaders(),...(state.session?{'X-CSRF-Token':state.session.csrf}:{})}});const received=await response.json();if(!response.ok)throw Error(received.error?.message||'Upload failed.');if(received.sha256!==sha)throw Error('Uploaded source digest does not match the selected file.');await request('/uploads/'+upload.upload_id+'/complete',{method:'POST',body:{sha256:sha}});source.upload_id=upload.upload_id;}
      acceptance={signature,file:fileIdentity,source,key:crypto.randomUUID()};}
      status.textContent='Accepting source…';const result=await request('/jobs',{method:'POST',body:source,headers:{'Idempotency-Key':acceptance.key}});acceptance=null;tickets.set(result.job_id,result.status_ticket);while(tickets.size>100)tickets.delete(tickets.keys().next().value);status.textContent='Source accepted.';form.elements.text.value='';form.elements.url.value='';form.elements.file.value='';await refresh();notice('Source accepted.');
    }catch(failure){status.textContent='';if(failure.name!=='AbortError')error.textContent=failure.message;}finally{for(const [node,disabled] of controls)node.disabled=disabled;}});};return poll(refresh,3000);
}
