import {state,$,$$,api,escape,handle,reorder,notice,pending,opaqueInput,closeDialogs} from './ui.js';
import {dashboard,vault,analytics,shares,documentation,shareCapabilities} from './views.js';
import {settings} from './settings.js';
import {crusher,clearCrusher} from './crusher.js';
const labels={dashboard:'Dashboard',vault:'Vault',crusher:'Crusher',analytics:'Analytics',shares:'Shares',settings:'Settings',documentation:'Documentation'};
let cleanup=()=>{},sequence=0,loginTimer=null,sessionTimer=null;
const mark='<img src="/assets/mark.svg" alt="" width="192" height="192">';
function clearView(){cleanup?.();cleanup=()=>{};clearTimeout(loginTimer);state.viewController?.abort();state.viewController=new AbortController();closeDialogs();}
function sidebarState(){const shell=$('.shell');if(!shell||!state.prefs)return;shell.classList.toggle('auto',state.prefs.sidebar==='auto');const sidebar=$('.sidebar'),hidden=matchMedia('(max-width:720px)').matches||state.prefs.sidebar==='auto';sidebar.inert=hidden&&!sidebar.classList.contains('revealed');}
function reveal(value){const sidebar=$('.sidebar');if(!sidebar)return;sidebar.classList.toggle('revealed',value);sidebar.inert=!value&&(state.prefs.sidebar==='auto'||matchMedia('(max-width:720px)').matches);let backdrop=$('.sidebar-backdrop');if(value&&matchMedia('(max-width:720px)').matches){if(!backdrop){backdrop=document.createElement('div');backdrop.className='sidebar-backdrop';backdrop.onclick=()=>reveal(false);$('.shell').append(backdrop);}}else backdrop?.remove();$$('[data-menu]').forEach(button=>button.setAttribute('aria-expanded',String(value)));}
function renderShell(){
  $('#app').innerHTML=`<div class="shell"><button class="edge-toggle" data-menu aria-label="Reveal navigation" aria-expanded="false">›</button><aside class="sidebar" aria-label="Main navigation"><div class="brand">${mark}<strong aria-label="Mastermind">Master<br>mind</strong></div><nav class="nav-list" aria-label="Primary navigation">${Object.entries(labels).filter(([id])=>id!=='documentation').map(([id,label])=>`<div class="nav-row" data-nav="${id}"><a href="/${id}">${label}</a><span class="ordinal"></span>${handle(label)}</div>`).join('')}</nav><div class="nav-bottom"><a href="/documentation">Documentation</a><button data-logout>Logout</button></div></aside><main class="shell-main"><header class="page-header"><h1></h1><button class="mobile-menu" data-menu aria-label="Open navigation" aria-expanded="false">Menu</button></header><div id="content" tabindex="-1"></div></main></div>`;
  reorder($('.nav-list'),'navigation','[data-nav]');sidebarState();$$('[data-menu]').forEach(b=>b.onclick=()=>reveal(!$('.sidebar').classList.contains('revealed')));$('.edge-toggle').onpointerenter=()=>reveal(true);$('.sidebar').onpointerleave=()=>{if(state.prefs.sidebar==='auto'&&!$('.sidebar').contains(document.activeElement))reveal(false);};$('.sidebar').onfocusout=()=>setTimeout(()=>{if(state.prefs.sidebar==='auto'&&!$('.sidebar').contains(document.activeElement))reveal(false);},0);
  $('[data-logout]').onclick=async e=>pending(e.target,async()=>{await api('/api/auth/logout',{method:'POST',body:{}});shareCapabilities.clear();clearCrusher();state.session=null;history.pushState(null,'','/login');await route();});
  $('.sidebar').addEventListener('keydown',e=>{if(e.key==='Escape'){reveal(false);$('[data-menu]:not(.edge-toggle)')?.focus();}});
}
async function login(){
  $('#app').innerHTML=`<main class="login" id="content"><div class="login-group"><div class="login-brand"><h1>Mastermind</h1>${mark}</div><section class="login-panel" aria-label="Owner login"><div class="reachability"><span data-reachability>Checking service</span><i class="status-square" aria-hidden="true"></i></div><form><label class="sr-only" for="access-key">Access Key</label><textarea class="secret" id="access-key" autocomplete="current-password" autocapitalize="off" spellcheck="false" placeholder="Access Key…" rows="1"></textarea><button type="submit">Enter service</button></form><p class="login-error" role="alert"></p></section></div></main>`;
  const input=$('#access-key'),value=opaqueInput(input);input.focus();let submitting=false;
  async function reachable(){if(!$('.login')?.isConnected)return;try{const result=await fetch('/healthz',{cache:'no-store',signal:state.viewController.signal});if(!result.ok)throw Error();$('.reachability').className='reachability success';$('[data-reachability]').textContent='Service reachable';}catch(error){if(error.name==='AbortError')return;$('.reachability').className='reachability danger';$('[data-reachability]').textContent='Service unreachable';}loginTimer=setTimeout(reachable,10000);}reachable();
  input.addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();$('form').requestSubmit();}});
  $('form').onsubmit=async e=>{e.preventDefault();if(submitting)return;submitting=true;await pending($('button[type=submit]'),async()=>{try{state.session=await api('/api/auth/login',{method:'POST',body:{access_key:value.value()},allow401:true});value.reset();state.prefs=await api('/api/owner/settings');history.replaceState(null,'','/'+(labels[state.route]?state.route:'dashboard'));await route();}catch(error){$('.login-error').textContent=error.message;}finally{submitting=false;}});};
}
async function route(){const current=++sequence;clearView();const requested=location.pathname.slice(1)||'dashboard';if(labels[requested])state.route=requested;
  if(!state.session){if(requested==='crusher'){$('#app').innerHTML=`<main id="content" class="public-crusher"><div class="brand-inline"><img src="/assets/mark.svg" alt="" width="64" height="64"><h1>Crusher</h1></div><div data-public-crusher></div></main>`;cleanup=await crusher($('[data-public-crusher]'),{publicOnly:true});return;}await login();return;}
  if(!$('.shell'))renderShell();sidebarState();$('.page-header h1').textContent=labels[state.route];document.title=labels[state.route]+' · Mastermind';$$('[data-nav]').forEach(row=>row.classList.toggle('active',row.dataset.nav===state.route));$('.nav-bottom a').classList.toggle('active',state.route==='documentation');reveal(false);const root=document.createElement('div');root.id='content';root.tabIndex=-1;$('#content').replaceWith(root);
  try{const fn={dashboard,vault,crusher,analytics,shares,settings,documentation}[state.route];const result=await fn(root);if(current!==sequence){result?.();return;}cleanup=result||(()=>{});}catch(error){if(error.name==='AbortError')return;root.innerHTML='<p class="danger" role="alert">'+escape(error.message)+'</p><button data-retry>Retry</button>';$('[data-retry]',root).onclick=route;}
}
document.addEventListener('click',e=>{const link=e.target.closest('a[href]');if(!link||e.ctrlKey||e.metaKey||e.shiftKey||e.altKey)return;const url=new URL(link.href);if(url.origin!==location.origin||!labels[url.pathname.slice(1)]||url.hash)return;e.preventDefault();history.pushState(null,'',url.pathname);route();});
document.addEventListener('preferences-changed',sidebarState);document.addEventListener('crusher-activated',route);document.addEventListener('session-expired',()=>{shareCapabilities.clear();clearCrusher();state.session=null;history.replaceState(null,'','/login');route();});document.addEventListener('credentials-rotated',()=>{shareCapabilities.clear();clearCrusher();});window.addEventListener('popstate',route);window.addEventListener('resize',sidebarState);
async function boot(){try{const appearance=await api('/api/appearance',{signal:null});document.documentElement.style.setProperty('--accent',appearance.accent);try{state.session=await api('/api/auth/session',{allow401:true,signal:null});state.prefs=await api('/api/owner/settings',{signal:null});}catch(error){if(error.status!==401)throw error;}await route();
  sessionTimer=setInterval(async()=>{if(state.session&&!document.hidden){try{await api('/api/auth/session',{signal:null});}catch(error){if(error.status!==401)notice('Session verification is temporarily unavailable.',true);}}},30000);
}catch(error){$('#app').innerHTML='<main id="content" class="initial"><p class="danger">'+escape(error.message)+'</p><button data-reload>Reconnect</button></main>';$('[data-reload]').onclick=()=>location.reload();}}
window.addEventListener('pagehide',()=>{clearView();clearInterval(sessionTimer);shareCapabilities.clear();clearCrusher();});boot();
