import {state,$,$$,api,escape,card,handle,reorder,poll,humanBytes,duration,stamp,search,wireSearch,bind,pending,dialog,confirmation,copyDialog,notice,download} from './ui.js';
import {startOperation} from './settings.js';
export const shareCapabilities=new Map();

function metric(id,title){return `<section class="card metric hoverable" data-card="${id}"><span class="ordinal"></span>${handle(title)}<h2>${escape(title)}</h2><div class="metric-value" data-value>Unknown</div><span class="metric-scope" data-scope></span>${id==='uptime'?'':'<div class="progress" role="progressbar" aria-label="'+escape(title)+'" aria-valuemin="0" aria-valuemax="100"><span></span></div>'}</section>`;}
export async function dashboard(root){
  root.innerHTML=`<div class="grid">${metric('cpu','CPU Usage')}${metric('ram','RAM Usage')}${metric('disk','Disk Usage')}${metric('uptime','Uptime')}${card('operations','Service status','<div data-status class="group">Checking Runtime and jobs…</div>',{wide:true})}</div>`;
  reorder($('.grid',root),'dashboard');return poll(async()=>{
    const [m,s,j]=await Promise.all([api('/api/owner/metrics'),api('/api/status'),api('/api/v1/crusher/jobs?limit=100')]);
    if(!root.isConnected)return;
    for(const id of ['cpu','ram','disk','uptime']){const c=$(`[data-card="${id}"]`,root),data=m[id];let value,scope;
      if(id==='uptime'){value='Active: '+duration(m.uptime_seconds);scope='Current Core process';}
      else if(id==='cpu'){value=(data?.percent==null?'Unknown':data.percent.toFixed(1)+'%')+' · cores: '+(data?.cores??'Unknown');scope='Server CPU';}
      else{value=data?`${data.percent==null?'Unknown':data.percent.toFixed(1)+'%'} · ${humanBytes(data.used)} / ${humanBytes(data.total)}`:'Unknown';scope=id==='disk'?'Canonical Vault filesystem · available to service':'Server RAM';}
      $('[data-value]',c).textContent=value;$('[data-scope]',c).textContent=scope;const progress=$('.progress',c);if(progress){const v=data?.percent;progress.firstChild.style.width=(v??0)+'%';if(v!=null)progress.setAttribute('aria-valuenow',Math.min(100,Math.max(0,v)));else progress.removeAttribute('aria-valuenow');progress.setAttribute('aria-valuetext',v==null?'Unknown':v.toFixed(1)+' percent');}
    }
    $('[data-status]',root).innerHTML=`<div class="status-line"><span>Mastermind · ${escape(s.status)}</span><span class="${s.status==='HEALTHY'?'success':'danger'}">Runtime ${s.runtime?.bridge?.ready?'ready':'unavailable'}</span></div><div class="row"><span>Active submissions: ${j.filter(x=>!['COMPLETED','FAILED','CANCELLED'].includes(x.state)).length}</span><span>Semantic index: ${escape(s.semantic_index?.state??s.semantic_index?.status??'Unknown')}</span><span>Sample: ${escape(stamp(m.sampled_at))}</span></div>${s.failure?`<p class="danger">${escape(s.failure)}</p>`:''}<p class="muted">Archive and mirror verification are shown in Settings → Backup.</p>`;
  },3000);
}

export async function analytics(root){
  root.innerHTML=`<div class="toolbar"><label>From<input type="date" data-first></label><label>Through<input type="date" data-last></label><button data-period>Apply period</button><span data-zone class="collection-info"></span></div><div class="grid">${card('heatmap','Activity Heatmap','<div class="heatmap-scroll"><div class="heatmap" role="group" aria-label="Daily owner activity"></div></div><p data-day-detail aria-live="polite">Select a day for its action count.</p><p class="muted">CREATE · EDIT · RENAME · MOVE. Intensity is relative to the busiest displayed day.</p>',{wide:true})}${['connectedness','notes','edges','broken'].map((id,i)=>card(id,['Connectedness','Notes','Internal edges','Broken references'][i],'<strong data-count class="accent">Unknown</strong>',{quarter:true})).join('')}</div>`;
  reorder($('.grid',root),'analytics');let selectedPeriod='';
  async function refresh(){const result=await api('/api/owner/analytics'+selectedPeriod);if(!root.isConnected)return;if(!$('[data-first]',root).value){$('[data-first]',root).value=result.first;$('[data-last]',root).value=result.last;}
    $('[data-zone]',root).textContent=result.timezone;$('.heatmap',root).innerHTML='<span aria-hidden="true"></span>'.repeat((new Date(result.first+'T12:00:00Z').getUTCDay()+6)%7)+result.days.map(day=>`<button type="button" class="day" data-level="${day.level}" aria-label="${day.date}: ${day.count} actions" title="${day.date}: ${day.count} actions" data-detail="${escape(day.date+': '+day.count+' actions · '+Object.entries(day.kinds).map(([k,v])=>k+' '+v).join(', '))}"></button>`).join('');
    for(const id of ['connectedness','notes','edges','broken'])$(`[data-card="${id}"] [data-count]`,root).textContent=result[id]+(id==='connectedness'?'%':'');}
  bind(root,'click','[data-period]',async(e,b)=>pending(b,async()=>{selectedPeriod='?'+new URLSearchParams({first:$('[data-first]',root).value,last:$('[data-last]',root).value});await refresh();}));
  bind(root,'click','.day',(e,b)=>$('[data-day-detail]',root).textContent=b.dataset.detail);return poll(refresh,15000);
}

export async function vault(root){
  root.innerHTML=`<section class="runtime" aria-label="Native Obsidian viewport"><div class="runtime-toolbar"><span class="state" role="status">Connecting to Runtime…</span><button data-reconnect>Reconnect</button><button data-fullscreen>Fullscreen</button><button data-portable>Download Vault copy</button></div><iframe title="Obsidian Runtime" allow="clipboard-read; clipboard-write; fullscreen"></iframe><div class="runtime-downloads" hidden></div></section>`;
  const runtime=$('.runtime',root),frame=$('iframe',root);const connect=()=>{frame.src='/runtime/index.html?autoconnect=1&path=runtime/websockify&resize=remote';};connect();let disconnected=false;
  bind(root,'click','[data-reconnect]',()=>{connect();notice('Runtime connection reopened.');});
  bind(root,'click','[data-fullscreen]',async()=>{if(document.fullscreenElement)await document.exitFullscreen();else await runtime.requestFullscreen();});
  const fullscreen=()=>{$('[data-fullscreen]',root).textContent=document.fullscreenElement?'Exit fullscreen':'Fullscreen';};document.addEventListener('fullscreenchange',fullscreen);
  bind(root,'click','[data-portable]',(e,b)=>pending(b,()=>startOperation('portable')));
  const stop=poll(async()=>{const [s,downloads]=await Promise.all([api('/api/status'),api('/api/runtime/downloads')]);if(!root.isConnected)return;const ready=s.runtime?.bridge?.ready&&s.runtime?.startup_allowed;$('.state',root).textContent=ready?'Obsidian connected':'Runtime recovering · '+(s.runtime_failure||s.failure||s.runtime?.state||'waiting');if(ready&&disconnected)connect();disconnected=!ready;
    const queue=$('.runtime-downloads',root);queue.hidden=!downloads.length;queue.innerHTML=downloads.map(item=>`<a download href="/api/owner/resources/content?${new URLSearchParams({path:item.path,download:'true'})}">Download ${escape(item.path.split('/').at(-1))}</a>`).join('');},3000);
  return()=>{stop();document.removeEventListener('fullscreenchange',fullscreen);frame.src='about:blank';};
}

export async function shares(root){
  root.innerHTML=`<div class="toolbar">${search('Search Shares','Filter this page by note, permission or state')}<div class="collection-info" data-count>Loading…</div><button data-create>Create Share</button><button data-previous disabled>Previous</button><button data-next>Next</button></div><div class="list" data-shares></div><p class="muted">A Share opens one current note. Links and resources are unavailable. A lost URL requires creating a new Share.</p>`;
  let records=[],offset=0,query='';const render=()=>{const list=records.filter(item=>(item.path+' '+item.permission+' '+item.state+' '+item.share_id).toLowerCase().includes(query.toLowerCase()));$('[data-count]',root).textContent=list.length+' of '+records.length+' on page '+(offset/100+1);
    $('[data-shares]',root).innerHTML=list.length?list.map(item=>`<div class="list-row" data-share="${item.share_id}"><div><p>${escape(item.path)}</p><small>${escape(item.permission)} · ${item.password_required?'Password protected':'No password'} · created ${escape(stamp(item.created_at))}<br>Expires: ${item.expires_at?escape(stamp(item.expires_at)):'Never'}</small></div><span class="${item.state==='active'?'success':'muted'}">${escape(item.state)}${item.target_missing?' · note missing':''}</span><div class="row-actions"><button data-copy ${!shareCapabilities.has(item.share_id)?'disabled title="URL is unavailable after reload. Create a new Share."':''}>Copy URL</button><button data-edit ${item.state==='revoked'?'disabled':''}>Policy</button><button data-revoke ${item.state==='revoked'?'disabled':''}>Revoke</button></div></div>`).join(''):'<p class="empty">No matching Shares.</p>';
    $('[data-previous]',root).disabled=!offset;$('[data-next]',root).disabled=records.length<100;};
  async function refresh(){records=await api('/api/v1/shares?limit=100&offset='+offset);if(root.isConnected)render();}wireSearch($('.search-box',root),value=>{query=value;render();});
  bind(root,'click','[data-previous]',async()=>{offset=Math.max(0,offset-100);await refresh();});bind(root,'click','[data-next]',async()=>{offset+=100;await refresh();});
  bind(root,'click','[data-copy]',(e,b)=>copyDialog('Share URL',shareCapabilities.get(b.closest('[data-share]').dataset.share)));
  bind(root,'click','[data-revoke]',(e,b)=>{const id=b.closest('[data-share]').dataset.share;confirmation('Revoke Share','This URL and its current sessions will stop working. Revocation cannot be undone.',async()=>{await api('/api/v1/shares/'+id,{method:'PATCH',body:{revoke:true}});shareCapabilities.delete(id);await refresh();},'Revoke Share');});
  async function edit(item){const creating=!item;const modal=dialog(creating?'Create Share':'Share policy',`<form>${creating?'<label>Note path<input name="path" required placeholder="Folder/Note.md" list="share-notes"><datalist id="share-notes"></datalist></label>':`<p>${escape(item.path)}</p>`}<label>Permission<select name="permission" aria-label="Permission"><option value="view">View</option><option value="edit">Edit</option></select></label><label>Expiration<select name="expires" aria-label="Expiration"><option value="unchanged">${creating?'Never':'Keep current expiration'}</option><option value="never">Never</option><option value="1">1 day</option><option value="7">7 days</option><option value="30">30 days</option><option value="365">365 days</option></select></label><label>Password action<select name="password_mode" aria-label="Password action"><option value="keep">${creating?'No password':'Keep existing password'}</option><option value="replace">Set a password</option>${creating?'':'<option value="remove">Remove password</option>'}</select></label><label data-password hidden>New Share password<input name="password" type="password" autocomplete="new-password" disabled></label><div class="dialog-footer"><button type="submit">${creating?'Create Share':'Apply policy'}</button></div></form>`);
    if(item)$('[name=permission]',modal.element).value=item.permission;
    $('[name=password_mode]',modal.element).onchange=e=>{const show=e.target.value==='replace';$('[data-password]',modal.element).hidden=!show;$('[name=password]',modal.element).disabled=!show;};
    if(creating)api('/api/notes?limit=500').then(notes=>{if(modal.element.isConnected)$('#share-notes',modal.element).innerHTML=notes.map(note=>`<option value="${escape(note.path)}"></option>`).join('');}).catch(()=>{if(modal.element.isConnected)modal.error.textContent='Suggestions unavailable. You can enter the exact note path.';});
    $('form',modal.element).onsubmit=async e=>{e.preventDefault();const form=e.target;await pending($('button[type=submit]',form),async()=>{try{const data={permission:form.elements.permission.value};if(creating)data.path=form.elements.path.value;
      const expiry=form.elements.expires.value;if(expiry==='never')data.expires_at=null;else if(expiry!=='unchanged')data.expires_at=Date.now()/1000+Number(expiry)*86400-1;
      const mode=form.elements.password_mode.value;if(mode==='replace')data.password=form.elements.password.value;else if(mode==='remove')data.password=null;
      const result=await api('/api/v1/shares'+(creating?'':'/'+item.share_id),{method:creating?'POST':'PATCH',body:data});modal.close(true);if(creating){shareCapabilities.set(result.share_id,result.url);copyDialog('Share URL',result.url);}await refresh();notice(creating?'Share created.':'Share policy updated.');}catch(error){modal.error.textContent=error.message;}});};}
  bind(root,'click','[data-create]',()=>edit(null));bind(root,'click','[data-edit]',(e,b)=>edit(records.find(item=>item.share_id===b.closest('[data-share]').dataset.share)));await refresh();return()=>{};
}

export async function documentation(root){
  const articles=await api('/api/owner/documentation');if(!root.isConnected)return()=>{};root.innerHTML=`<div class="docs"><nav class="docs-nav" aria-label="Documentation">${search('Search documentation')}<div data-articles></div></nav><article class="article" aria-label="Operator guide"></article></div>`;let selected=location.hash.slice(1)||articles[0].id;
  const show=id=>{const item=articles.find(article=>article.id===id)||articles[0];selected=item.id;$('.article',root).innerHTML=`<small>Mastermind / Operator guide</small><h2>${escape(item.title)}</h2>${item.html}`;$$('[data-article]',root).forEach(link=>link.classList.toggle('active',link.dataset.article===selected));};
  function filter(query){const matches=articles.filter(item=>(item.title+' '+item.text).toLowerCase().includes(query.toLowerCase()));$('[data-articles]',root).innerHTML=matches.length?matches.map(item=>`<a href="#${item.id}" data-article="${item.id}" class="${item.id===selected?'active':''}">${escape(item.title)}</a>`).join(''):'<p class="muted">No matching articles.</p>';}
  wireSearch($('.search-box',root),filter);filter('');show(selected);bind(root,'click','[data-article]',(e,a)=>{e.preventDefault();history.replaceState(null,'','#'+a.dataset.article);show(a.dataset.article);});return()=>{};
}
