"""Generate the full Unicode folding table using the same pinned Python as Core."""
import json
import unicodedata
from pathlib import Path

target = Path(__file__).resolve().parents[1] / '.local/services/neptune/src/Neptune.Core/UnicodeNames.cs'
rows = []
for code in range(0x110000):
    char = chr(code)
    if char.casefold() != char:
        rows.append(f'        [{code}] = {json.dumps(char.casefold(), ensure_ascii=True)},')
target.write_text('''// Generated by Mastermind scripts/generate_neptune_casefold.py; Unicode '''+unicodedata.unidata_version+'''.
using System.Text;
namespace Neptune.Core;
public static class UnicodeNames
{
    private static readonly IReadOnlyDictionary<int, string> Fold = new Dictionary<int, string>
    {
'''+ '\n'.join(rows)+'''
    };
    public static string Key(string text)
    {
        var output = new StringBuilder(text.Length);
        foreach (var rune in text.Normalize(NormalizationForm.FormC).EnumerateRunes())
            output.Append(Fold.TryGetValue(rune.Value, out var folded) ? folded : rune.ToString());
        return output.ToString();
    }
}
''', encoding='utf-8')
print(f'Generated {len(rows)} Unicode {unicodedata.unidata_version} folding entries.')
