const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
const {chromium}=require('./lib/browser.cjs');
const origin='http://localhost:18390',out=path.resolve('artifacts/public-editing-20260919');fs.mkdirSync(out,{recursive:true});
(async()=>{
 const browser=await chromium.launch({headless:true}),owner=await browser.newContext(),visitor=await browser.newContext({viewport:{width:1920,height:1080}}),page=await visitor.newPage();let session;const results={},errors=[];page.on('pageerror',e=>errors.push(e.message));
 try{
  const response=await owner.request.post(origin+'/api/auth/login',{headers:{Origin:origin},data:{access_key:fs.readFileSync('.local/secrets/core/bootstrap_access_key','utf8')}});assert.ok(response.ok());session=await response.json();
  const codeResponse=await owner.request.post(origin+'/api/v1/crusher/access',{headers:{Origin:origin,'X-CSRF-Token':session.csrf},data:{}});assert.ok(codeResponse.ok());const access=await codeResponse.json();
  const appearance=await (await owner.request.get(origin+'/api/appearance')).json();
  await page.goto(origin+'/crusher');await page.getByLabel('Crusher access code',{exact:true}).waitFor();assert.equal((await page.locator('.gate-group').boundingBox()).width,255);assert.equal(await page.locator('h1').count(),0);await page.getByText('Service reachable',{exact:true}).waitFor();await page.screenshot({path:path.join(out,'crusher-locked.png')});
  await page.getByLabel('Crusher access code').fill(access.code);await page.getByRole('button',{name:'Enter',exact:true}).click();await page.getByRole('heading',{name:'mastermind crusher'}).waitFor();assert.equal(await page.locator('select').count(),0);assert.equal(await page.evaluate(()=>getComputedStyle(document.documentElement).getPropertyValue('--accent').trim().toUpperCase()),appearance.accent.toUpperCase());
  const submissions=[],body=Buffer.from('Small browser drop fixture.\n'),sha=crypto.createHash('sha256').update(body).digest('hex');
  await page.route('**/api/v1/crusher/jobs**',async route=>{if(route.request().method()==='POST'){const source=route.request().postDataJSON(),id=crypto.randomBytes(16).toString('hex');submissions.push({job_id:id,source,source_label:source.type==='upload'?'Dropped file':source.url,state:'QUEUED',stage:'QUEUED',progress_percent:0,created_at:Date.now()/1000});await route.fulfill({json:{job_id:id,status_ticket:'browser-fixture-ticket'}});}else await route.fulfill({json:submissions});});
  await page.route('**/api/v1/crusher/uploads',route=>route.fulfill({json:{upload_id:'browser-upload'}}));
  await page.route('**/api/v1/crusher/uploads/browser-upload/content',route=>route.fulfill({json:{sha256:sha}}));
  await page.route('**/api/v1/crusher/uploads/browser-upload/complete',route=>route.fulfill({json:{completed:true}}));
  await page.screenshot({path:path.join(out,'crusher-unlocked.png')});
  await page.getByLabel('Source links',{exact:true}).fill('https://example.com/article\nhttps://youtu.be/dQw4w9WgXcQ\nhttps://github.com/example/repository');await page.getByRole('button',{name:'Submit links'}).click();await page.getByText('3 sources accepted.',{exact:true}).first().waitFor();assert.deepEqual(submissions.map(item=>item.source.type),['url','youtube','git']);assert.equal(await page.getByLabel('Source links').inputValue(),'');
  const transfer=await page.evaluateHandle(()=>{const data=new DataTransfer();data.items.add(new File(['Small browser drop fixture.\n'],'source.txt',{type:'text/plain'}));return data;});
  await page.dispatchEvent('body','dragenter',{dataTransfer:transfer});await page.locator('.file-drag-overlay').waitFor({state:'visible'});await page.waitForTimeout(190);await page.screenshot({path:path.join(out,'crusher-drag-overlay.png')});await page.dispatchEvent('body','dragover',{dataTransfer:transfer});await page.dispatchEvent('body','drop',{dataTransfer:transfer});await page.locator('.file-drag-overlay').waitFor({state:'hidden'});await page.getByText('1 source accepted.',{exact:true}).first().waitFor();assert.equal(submissions.at(-1).source.type,'upload');
  await page.locator('input[type=file]').setInputFiles({name:'picked.txt',mimeType:'text/plain',buffer:body});await page.waitForFunction(()=>document.querySelectorAll('.job').length===5);assert.equal(submissions.length,5);results.inputs='PASS: real activation, automatic URL types, drag/drop overlay and file picker; source transport responses are browser fixtures';
  const publicSearch=await visitor.request.get(origin+'/api/notes');assert.equal(publicSearch.status(),401);results.scope='PASS: activated visitor cannot browse Vault';
  for(const width of [390,720,1440]){await page.setViewportSize({width,height:900});await page.waitForTimeout(200);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);await page.screenshot({path:path.join(out,`crusher-${width}.png`)});}
  assert.deepEqual(errors,[]);results.accent='PASS';results.responsive='PASS';results.browser_errors=[];fs.writeFileSync(path.join(out,'crusher-result.json'),JSON.stringify(results,null,2));console.log(JSON.stringify(results,null,2));
 }finally{if(session)await owner.request.post(origin+'/api/auth/logout',{headers:{Origin:origin,'X-CSRF-Token':session.csrf},data:{}}).catch(()=>{});await browser.close();}
})().catch(error=>{console.error(error);process.exitCode=1;});
