"""Exercise manual Vault ZIP download/restore through real Core HTTP and Chromium.

Uses a marked, disposable synthetic home and offline Runtime coordination.
Never connects to an owner's Core, Vault or neighboring services.
"""
import base64
import hashlib
import json
import os
import socket
import subprocess
import sys
import threading
import time
import uuid
import zipfile
from dataclasses import replace
from pathlib import Path

import pyrage
import uvicorn
from cryptography.hazmat.primitives.asymmetric.ed25519 import Ed25519PrivateKey
from cryptography.hazmat.primitives.serialization import Encoding, NoEncryption, PrivateFormat, PublicFormat

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from mastermind.api import create_app
from mastermind.bridge_artifacts import install_bridge_files
from mastermind.config import Config
from mastermind.fs import atomic_write, file_inventory


def main():
    work = ROOT / ".local/qualification" / ("vault-archive-"+uuid.uuid4().hex[:12])
    config = Config(work / "data", runtime_mode="offline", test_mode=True, secret_directory=work / "secrets",
                    secret_backend="development-files", bridge_artifacts=ROOT / "bridge/dist")
    files = {"root/root.md": b"#main\n[[Birds]]\n", "root/Animals/Birds.md": "#key\nПтицы\n@root".encode(),
             "attachments/image.bin": bytes(range(256))*1024,
             ".obsidian/appearance.json": b'{"cssTheme":"Fixture only"}',
             ".obsidian/app.json": b'{"alwaysUpdateLinks":true}',
             ".obsidian/plugins/fixture/data.json": b'{"opaque":"test plugin data"}'}
    for name, value in files.items():
        atomic_write(config.vault / name, value)
    (config.vault / "empty/nested").mkdir(parents=True)
    install_bridge_files(config.vault, config.bridge_artifacts)
    identity, key = pyrage.x25519.Identity.generate(), Ed25519PrivateKey.generate()
    secrets = {"bootstrap_access_key": "synthetic-vault-archive-key", "bridge_token": "synthetic-bridge-only",
               "recovery_identity": str(identity), "recovery_recipient": str(identity.to_public()),
               "backup_signing_private": base64.b64encode(key.private_bytes(Encoding.Raw, PrivateFormat.Raw, NoEncryption())).decode(),
               "backup_signing_public": base64.b64encode(key.public_key().public_bytes(Encoding.Raw, PublicFormat.Raw)).decode()}
    for name, value in secrets.items():
        atomic_write(config.secret_directory / name, value.encode())
    sock = socket.socket()
    sock.bind(("127.0.0.1", 0))
    config = replace(config, public_url="http://127.0.0.1:"+str(sock.getsockname()[1]))
    atomic_write(work / "fixture.json", json.dumps({"fixture": "mastermind-vault-archive/v1", "origin": config.public_url}).encode())
    application = create_app(config)
    server = uvicorn.Server(uvicorn.Config(application, log_level="error", access_log=False))
    thread = threading.Thread(target=server.run, kwargs={"sockets": [sock]}, daemon=True)
    thread.start()
    try:
        deadline = time.monotonic()+30
        while not server.started and thread.is_alive() and time.monotonic() < deadline:
            time.sleep(.05)
        if not server.started:
            raise RuntimeError("Synthetic Core did not start")
        expected = {name: hashlib.sha256(path.read_bytes()).hexdigest() for name, path in file_inventory(config.vault)}
        subprocess.run(["node", "scripts/probe_vault_archive.cjs", str(work)], cwd=ROOT, check=True, timeout=120)
        with zipfile.ZipFile(work / "vault.zip") as archive:
            downloaded = {i.filename: hashlib.sha256(archive.read(i)).hexdigest() for i in archive.infolist() if not i.is_dir()}
            assert "empty/nested/" in archive.namelist()
        assert downloaded == expected, "ZIP must contain the exact Vault root"
        assert {name: hashlib.sha256(path.read_bytes()).hexdigest() for name, path in file_inventory(config.vault)} == expected
        assert (config.vault / "empty/nested").is_dir()
        print("PASS byte-for-byte exported/restored Vault, native settings, plugin data and empty folders", flush=True)
    finally:
        server.should_exit = True
        thread.join(timeout=30)
        sock.close()
        # Only synthetic fixture secrets, generated by this invocation.
        for name in secrets:
            (config.secret_directory / name).unlink(missing_ok=True)
    print(json.dumps({"fixture": str(work), "status": "PASS", "runtime": "offline coordination; no native Obsidian"}))
    return 0


if __name__ == "__main__":
    os.environ.setdefault("PYTHONUTF8", "1")
    raise SystemExit(main())
